"""tables

Revision ID: da344ce58416
Revises: 
Create Date: 2024-01-22 16:52:14.397294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da344ce58416'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=1000), nullable=False),
    sa.Column('environment', sa.String(length=1000), nullable=False),
    sa.Column('hostname', sa.String(length=1000), nullable=False),
    sa.Column('alias', sa.String(length=1000), nullable=False),
    sa.Column('replicaset', sa.String(length=1000), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('team', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databases_types')
    # ### end Alembic commands ###
